version: 2
jobs:
  build:
    working_directory: /go/src/github.com/yusukemisa/goNewProject
    docker:
      - image: circleci/golang:1.9.2
    steps:
      - checkout
      - run: echo 'ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ START BUILD ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£'
      - run: go get -u golang.org/x/lint/golint github.com/golang/dep/cmd/dep
      - run: golint ./...
      - run: go vet ./...
      - run: go test -v -race ./...
      - run: echo 'ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ END BUILD ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£ğŸ£'
